# Generated by Django 4.2 on 2023-04-27 11:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(choices=[('TA', 'Танк'), ('HE', 'Хиллер'), ('DD', 'Дамагер'), ('ME', 'Торговец'), ('GU', 'Гилдмастер'), ('QU', 'Квестодатель'), ('BS', 'Кузнец'), ('LE', 'Кожевник'), ('PO', 'Зельевар'), ('MA', 'Заклинатель')], default='DD', max_length=2, verbose_name='Категория персонажа')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(error_messages='Новость с таким заголовком уже есть', max_length=128, unique=True)),
                ('text', models.TextField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(error_messages={'unique': 'Никнейм занят'}, max_length=64, unique=True, verbose_name='Никнейм')),
                ('mail', models.EmailField(max_length=254)),
                ('date_registration', models.DateTimeField(auto_now_add=True)),
                ('user_player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply_text', models.TextField()),
                ('reply_date_creation', models.DateTimeField(auto_now_add=True)),
                ('reply_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billboard.post')),
                ('reply_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PostCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_through', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billboard.category')),
                ('post_through', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billboard.post')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billboard.userprofile'),
        ),
        migrations.AddField(
            model_name='post',
            name='post_category',
            field=models.ManyToManyField(through='billboard.PostCategory', to='billboard.category'),
        ),
    ]
