# Generated by Django 4.2 on 2023-05-02 16:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('billboard', '0004_remove_userprofile_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='status',
            field=models.BooleanField(default=False, verbose_name='status_reply'),
        ),
        migrations.AlterField(
            model_name='reply',
            name='reply_date_creation',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='reply',
            name='reply_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relpy_post', to='billboard.post', verbose_name='post_reply'),
        ),
        migrations.AlterField(
            model_name='reply',
            name='reply_text',
            field=models.TextField(verbose_name='text_reply'),
        ),
        migrations.AlterField(
            model_name='reply',
            name='reply_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user_reply'),
        ),
    ]
