# Generated by Django 4.2 on 2023-05-02 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billboard', '0005_reply_status_alter_reply_reply_date_creation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='reply_text',
            field=models.TextField(verbose_name='Текст комментария'),
        ),
    ]
