# Generated by Django 4.2 on 2023-05-02 16:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('billboard', '0006_alter_reply_reply_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='reply_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relpy_post', to='billboard.post', verbose_name='Статья'),
        ),
        migrations.AlterField(
            model_name='reply',
            name='reply_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор комментария'),
        ),
    ]
