# Generated by Django 4.2 on 2023-05-02 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billboard', '0007_alter_reply_reply_post_alter_reply_reply_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reply',
            old_name='reply_text',
            new_name='text',
        ),
    ]
