# Generated by Django 4.2 on 2023-05-05 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billboard', '0011_alter_post_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
