# Generated by Django 4.2 on 2023-05-05 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billboard', '0012_delete_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content',
            field=models.FileField(blank=True, upload_to='content/'),
        ),
    ]
